import React from "react";

interface ResponseCardProps {
    query: string;
    response: string;
    modelUsed?: string;
}

export default function ResponseCard({ query, response, modelUsed }: ResponseCardProps) {
    if (!query && !response) return null;

    return (
        <div className="w-full max-w-2xl mx-auto mt-8 flex flex-col gap-6 animate-[slideUpFade_0.6s_ease-out_forwards]">

            {/* Right-aligned Question Block */}
            {query && (
                <div className="flex justify-end w-full">
                    <div className="max-w-[85%]">
                        <p className="text-[15px] leading-relaxed text-neutral-800 font-medium pb-2 text-right">
                            {query}
                        </p>
                    </div>
                </div>
            )}

            {/* Left-aligned Answer Card */}
            {response && (
                <div className="flex flex-col w-full bg-white rounded-3xl p-6 md:p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-neutral-100">
                    <div className="prose prose-neutral prose-sm max-w-none text-[15px] leading-relaxed text-neutral-600 whitespace-pre-wrap">
                        {response}
                    </div>

                    {modelUsed && (
                        <div className="mt-8 flex items-center gap-2 text-[11px] font-medium tracking-wide text-neutral-400 uppercase">
                            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400/80"></span>
                            Generated by {modelUsed}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
